version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: inventory_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: inventory_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse:25.4
    container_name: clickhouse-inventory_db
    restart: always
    environment:
      CLICKHOUSE_DB: inventory_db
      CLICKHOUSE_USER: username
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"  # HTTP-интерфейс
      - "9000:9000"  # Native TCP-интерфейс
    volumes:
      - clickhouse_temp_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/cl
      - ./clickhouse/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  clickhouse_temp_data:
  clickhouse_logs: