"""
This type stub file was generated by pyright.
"""

from application.model import Model
from application.view import View

class Controller:
    def __init__(self, model: Model, view: View) -> None:
        ...
    


