"""
This type stub file was generated by pyright.
"""

from typing import Any

class Model:
    def __init__(self) -> None:
        ...
    
    def load_from_txt(self, input_file: Any): # -> None:
        ...
    
    def export_to_excel(self): # -> None:
        ...
    


